type: docker
kind: pipeline
name: default

steps: 

# Loaf.Core 编译、发布Nuget
- name: Loaf.Core 构建Nuget包
  image: mcr.microsoft.com/dotnet/sdk:6.0
  environment:
    API_KEY:
      from_secret: nugetkey
    NUGET_URL:
      from_secret: nugeturl
    API_KEY2:
      from_secret: nugetkey2
    NUGET_URL2:
      from_secret: nugeturl2
  commands: 
  - rm -rf ./publish
  - dotnet restore
  - dotnet pack -c Release -o ./publish/nupkgs -p:PackageVersion=$DRONE_TAG
  - dotnet nuget push -s $NUGET_URL -k $API_KEY "./publish/nupkgs/*.nupkg" 
  - dotnet nuget push "./publish/nupkgs/*.nupkg" -k $API_KEY2  -s $NUGET_URL2
trigger:
  event:
  - tag