type: docker
kind: pipeline
name: default

steps:
- name: 后端
  image: mcr.microsoft.com/dotnet/sdk:6.0
  commands:  
  - dotnet build ./applications/Loaf.Admin/Loaf.Admin.csproj -c Release
  - dotnet publish ./applications/Loaf.Admin/Loaf.Admin.csproj -c Release -o ./publish/LoafAdmin

- name: 构建镜像  
  image: plugins/docker
  volumes:
  - name: docker
    path: /var/run/docker.sock
  settings:
    username: 
      from_secret: docker_user
    password: 
      from_secret: docker_pass
    repo: loaf-admin
    registry: registry.cn-zhangjiakou.aliyuncs.com
    tags: ${DRONE_COMMIT_BRANCH}-${DRONE_BUILD_NUMBER}

trigger:
  event:
  - tag